name: CI

on: [push]

jobs:
  gatsby-for-percy:
    name: Lost Pixel screenshots via Gatsby build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
      - run: npm ci
      # - name: Caching Gatsby
      #   id: gatsby-cache-build
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       public
      #       .cache
      #     key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
      #     restore-keys: |
      #       ${{ runner.os }}-gatsby-build-
      - name: Build Gatsby app
        # run: npx gatsby build --prefix-paths
        # env:
        #   GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
        #   CI: true

      - name: Run Gatsby app
        run: npx gatsby serve --host 172.17.0.1 &

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@cdb28d05cdfd9ed32ff4d9f002bd8c823d3e95c6
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
